# Sección 2 — Inventario NASA OSDR

Objetivo:
Construir un inventario reproducible de estudios de Arabidopsis thaliana disponibles en NASA OSDR/GeneLab.

Fuente:
NASA OSDR Biological Data API.

In [1]:
import pandas as pd
import requests
from io import StringIO

BASE_URL = "https://visualization.osdr.nasa.gov/biodata/api/v2/query/metadata/"

params = {
    "study.characteristics.organism": "Arabidopsis thaliana",
    "id.accession": ""
}

response = requests.get(BASE_URL, params=params, timeout=60)

print("Status code:", response.status_code)
print("URL:", response.url)

Status code: 200
URL: https://visualization.osdr.nasa.gov/biodata/api/v2/query/metadata/?study.characteristics.organism=Arabidopsis+thaliana&id.accession=

In [2]:
print(response.text[:1000])

id.accession,id.assay name,id.sample name,study.characteristics.organism
"OSD-7","OSD-7_transcription-profiling_dna-microarray_affymetrix","Atha_WS-0_Col-0_Hypocotyl_FLT_Rep1","Arabidopsis thaliana"
"OSD-7","OSD-7_transcription-profiling_dna-microarray_affymetrix","Atha_WS-0_Col-0_Hypocotyl_FLT_Rep2","Arabidopsis thaliana"
"OSD-7","OSD-7_transcription-profiling_dna-microarray_affymetrix","Atha_WS-0_Col-0_Hypocotyl_FLT_Rep3","Arabidopsis thaliana"
"OSD-7","OSD-7_transcription-profiling_dna-microarray_affymetrix","Atha_WS-0_Col-0_Hypocotyl_FLT_Rep4","Arabidopsis thaliana"
"OSD-7","OSD-7_transcription-profiling_dna-microarray_affymetrix","Atha_WS-0_Col-0_Hypocotyl_FLT_Rep5","Arabidopsis thaliana"
"OSD-7","OSD-7_transcription-profiling_dna-microarray_affymetrix","Atha_WS-0_Col-0_Hypocotyl_GC_Rep1","Arabidopsis thaliana"
"OSD-7","OSD-7_transcription-profiling_dna-microarray_affymetrix","Atha_WS-0_Col-0_Hypocotyl_GC_Rep2","Arabidopsis thaliana"
"OSD-7","OSD-7_transcription-profiling_

In [3]:
df = pd.read_csv(StringIO(response.text))

print("Filas:", len(df))
print("Columnas:", len(df.columns))

df.head()

Filas: 2204
Columnas: 4

,id.accession,id.assay name,id.sample name,study.characteristics.organism
0,OSD-7,OSD-7_transcription-profiling_dna-microarray_a...,Atha_WS-0_Col-0_Hypocotyl_FLT_Rep1,Arabidopsis thaliana
1,OSD-7,OSD-7_transcription-profiling_dna-microarray_a...,Atha_WS-0_Col-0_Hypocotyl_FLT_Rep2,Arabidopsis thaliana
2,OSD-7,OSD-7_transcription-profiling_dna-microarray_a...,Atha_WS-0_Col-0_Hypocotyl_FLT_Rep3,Arabidopsis thaliana
3,OSD-7,OSD-7_transcription-profiling_dna-microarray_a...,Atha_WS-0_Col-0_Hypocotyl_FLT_Rep4,Arabidopsis thaliana
4,OSD-7,OSD-7_transcription-profiling_dna-microarray_a...,Atha_WS-0_Col-0_Hypocotyl_FLT_Rep5,Arabidopsis thaliana

In [4]:
df.columns.tolist()

['id.accession',
 'id.assay name',
 'id.sample name',
 'study.characteristics.organism']

In [5]:
df.head()

,id.accession,id.assay name,id.sample name,study.characteristics.organism
0,OSD-7,OSD-7_transcription-profiling_dna-microarray_a...,Atha_WS-0_Col-0_Hypocotyl_FLT_Rep1,Arabidopsis thaliana
1,OSD-7,OSD-7_transcription-profiling_dna-microarray_a...,Atha_WS-0_Col-0_Hypocotyl_FLT_Rep2,Arabidopsis thaliana
2,OSD-7,OSD-7_transcription-profiling_dna-microarray_a...,Atha_WS-0_Col-0_Hypocotyl_FLT_Rep3,Arabidopsis thaliana
3,OSD-7,OSD-7_transcription-profiling_dna-microarray_a...,Atha_WS-0_Col-0_Hypocotyl_FLT_Rep4,Arabidopsis thaliana
4,OSD-7,OSD-7_transcription-profiling_dna-microarray_a...,Atha_WS-0_Col-0_Hypocotyl_FLT_Rep5,Arabidopsis thaliana

In [6]:
study_inventory = (
    df.groupby("id.accession", as_index=False)
      .agg(
          organism=("study.characteristics.organism", "first"),
          n_samples=("id.sample name", "nunique"),
          n_assays=("id.assay name", "nunique"),
          assay_names=("id.assay name", lambda x: " | ".join(sorted(set(x))))
      )
)

study_inventory.head(10)

,id.accession,organism,n_samples,n_assays,assay_names
0,OSD-120,Arabidopsis thaliana,90,2,OSD-120_image-analysis_photography_cara | OSD-...
1,OSD-121,Arabidopsis thaliana,6,3,OSD-121_glycomic-profile_elisa_thermo fisher s...
2,OSD-134,Arabidopsis thaliana,33,1,OSD-134_transcription-profiling_dna-microarray...
3,OSD-136,Arabidopsis thaliana,9,1,OSD-136_transcription-profiling_dna-microarray...
4,OSD-144,Arabidopsis thaliana,24,1,OSD-144_transcription-profiling_dna-microarray...
5,OSD-147,Arabidopsis thaliana,18,1,OSD-147_transcription-profiling_dna-microarray...
6,OSD-16,Arabidopsis thaliana,8,1,OSD-16_protein-expression-profiling_mass-spect...
7,OSD-17,Arabidopsis thaliana,24,1,OSD-17_transcription-profiling_dna-microarray_...
8,OSD-193,Arabidopsis thaliana,32,1,OSD-193_transcription-profiling_rna-sequencing...
9,OSD-205,Arabidopsis thaliana,16,1,OSD-205_transcription-profiling_dna-microarray...

In [7]:
print("Número de estudios únicos:", study_inventory["id.accession"].nunique())

Número de estudios únicos: 62

In [8]:
study_inventory["id.accession"].tolist()

['OSD-120',
 'OSD-121',
 'OSD-134',
 'OSD-136',
 'OSD-144',
 'OSD-147',
 'OSD-16',
 'OSD-17',
 'OSD-193',
 'OSD-205',
 'OSD-208',
 'OSD-210',
 'OSD-217',
 'OSD-218',
 'OSD-219',
 'OSD-22',
 'OSD-223',
 'OSD-251',
 'OSD-281',
 'OSD-282',
 'OSD-296',
 'OSD-313',
 'OSD-314',
 'OSD-320',
 'OSD-321',
 'OSD-329',
 'OSD-346',
 'OSD-37',
 'OSD-38',
 'OSD-406',
 'OSD-411',
 'OSD-416',
 'OSD-427',
 'OSD-428',
 'OSD-434',
 'OSD-436',
 'OSD-437',
 'OSD-44',
 'OSD-45',
 'OSD-450',
 'OSD-46',
 'OSD-476',
 'OSD-480',
 'OSD-496',
 'OSD-498',
 'OSD-502',
 'OSD-508',
 'OSD-510',
 'OSD-518',
 'OSD-519',
 'OSD-520',
 'OSD-522',
 'OSD-531',
 'OSD-565',
 'OSD-615',
 'OSD-624',
 'OSD-625',
 'OSD-658',
 'OSD-678',
 'OSD-7',
 'OSD-782',
 'OSD-8']

In [9]:
def classify_omics(assay_name):
    assay = assay_name.lower()

    if "rna-seq" in assay or "rna sequencing" in assay:
        return "RNA-seq"

    elif "microarray" in assay:
        return "Microarray"

    elif "bisulfite" in assay or "methyl" in assay:
        return "Epigenomics"

    elif "proteom" in assay:
        return "Proteomics"

    elif "metabolom" in assay:
        return "Metabolomics"

    elif "small rna" in assay or "mirna" in assay:
        return "Small RNA-seq"

    else:
        return "Other"

In [10]:
study_inventory["omics_type"] = study_inventory["assay_names"].apply(classify_omics)

study_inventory[
    ["id.accession", "omics_type", "n_samples", "n_assays", "assay_names"]
].head(20)

,id.accession,omics_type,n_samples,n_assays,assay_names
0,OSD-120,RNA-seq,90,2,OSD-120_image-analysis_photography_cara | OSD-...
1,OSD-121,Microarray,6,3,OSD-121_glycomic-profile_elisa_thermo fisher s...
2,OSD-134,Microarray,33,1,OSD-134_transcription-profiling_dna-microarray...
3,OSD-136,Microarray,9,1,OSD-136_transcription-profiling_dna-microarray...
4,OSD-144,Microarray,24,1,OSD-144_transcription-profiling_dna-microarray...
5,OSD-147,Microarray,18,1,OSD-147_transcription-profiling_dna-microarray...
6,OSD-16,Other,8,1,OSD-16_protein-expression-profiling_mass-spect...
7,OSD-17,Microarray,24,1,OSD-17_transcription-profiling_dna-microarray_...
8,OSD-193,RNA-seq,32,1,OSD-193_transcription-profiling_rna-sequencing...
9,OSD-205,Microarray,16,1,OSD-205_transcription-profiling_dna-microarray...
10,OSD-208,RNA-seq,6,2,OSD-208_transcription-profiling_dna-microarray...
11,OSD-210,Other,5,1,gse121111_genome_sequencing_nucleotide_sequencing
12,OSD-217,RNA-seq,24,2,OSD-217_DNA-methylation-profiling_Whole-Genome...
13,OSD-218,RNA-seq,32,1,OSD-218_transcription-profiling_rna-sequencing...
14,OSD-219,RNA-seq,32,1,gse95373_transcription_profiling_RNA_Sequencin...
15,OSD-22,Microarray,20,1,OSD-22_transcription-profiling_dna-microarray_...
16,OSD-223,RNA-seq,40,1,OSD-223_transcription-profiling_rna-sequencing...
17,OSD-251,RNA-seq,20,1,OSD-251_transcription-profiling_rna-sequencing...
18,OSD-281,RNA-seq,32,1,OSD-281_transcription-profiling_rna-sequencing...
19,OSD-282,Microarray,8,1,OSD-282_transcription-profiling_dna-microarray...

In [11]:
study_inventory["omics_type"].value_counts()

omics_type
RNA-seq        33
Microarray     22
Other           4
Epigenomics     3
Name: count, dtype: int64

In [12]:
apex_candidates = study_inventory[
    study_inventory["id.accession"].isin([
        "OSD-615",
        "OSD-218",
        "OSD-217",
        "OSD-427",
        "OSD-416",
        "OSD-625",
        "OSD-38",
        "OSD-121"
    ])
]

apex_candidates

,id.accession,organism,n_samples,n_assays,assay_names,omics_type
1,OSD-121,Arabidopsis thaliana,6,3,OSD-121_glycomic-profile_elisa_thermo fisher s...,Microarray
12,OSD-217,Arabidopsis thaliana,24,2,OSD-217_DNA-methylation-profiling_Whole-Genome...,RNA-seq
13,OSD-218,Arabidopsis thaliana,32,1,OSD-218_transcription-profiling_rna-sequencing...,RNA-seq
28,OSD-38,Arabidopsis thaliana,36,2,OSD-38_protein-expression-profiling_mass-spect...,RNA-seq
31,OSD-416,Arabidopsis thaliana,48,1,OSD-416_dna-methylation-profiling_bisulfite-se...,Epigenomics
32,OSD-427,Arabidopsis thaliana,48,1,OSD-427_transcription-profiling_rna-sequencing...,RNA-seq
54,OSD-615,Arabidopsis thaliana,12,1,OSD-615_glycomic-profile_elisa_thermo fisher s...,Other
56,OSD-625,Arabidopsis thaliana,16,1,OSD-625_targeted-dna-methylation-profiling_ccs...,Epigenomics

In [13]:
rna_seq_studies = study_inventory[
    study_inventory["omics_type"] == "RNA-seq"
]

rna_seq_studies[
    ["id.accession", "n_samples", "n_assays", "assay_names"]
]

,id.accession,n_samples,n_assays,assay_names
0,OSD-120,90,2,OSD-120_image-analysis_photography_cara | OSD-...
8,OSD-193,32,1,OSD-193_transcription-profiling_rna-sequencing...
10,OSD-208,6,2,OSD-208_transcription-profiling_dna-microarray...
12,OSD-217,24,2,OSD-217_DNA-methylation-profiling_Whole-Genome...
13,OSD-218,32,1,OSD-218_transcription-profiling_rna-sequencing...
14,OSD-219,32,1,gse95373_transcription_profiling_RNA_Sequencin...
16,OSD-223,40,1,OSD-223_transcription-profiling_rna-sequencing...
17,OSD-251,20,1,OSD-251_transcription-profiling_rna-sequencing...
18,OSD-281,32,1,OSD-281_transcription-profiling_rna-sequencing...
21,OSD-313,18,1,OSD-313_transcription-profiling_rna-sequencing...
22,OSD-314,17,1,OSD-314_transcription-profiling_rna-sequencing...
24,OSD-321,44,1,OSD-321_transcription-profiling_rna-sequencing...
26,OSD-346,36,1,OSD-346_transcription-profiling_rna-sequencing...
27,OSD-37,56,1,OSD-37_transcription-profiling_rna-sequencing-...
28,OSD-38,36,2,OSD-38_protein-expression-profiling_mass-spect...
29,OSD-406,24,1,OSD-406_transcription-profiling_rna-sequencing...
30,OSD-411,64,1,OSD-411_transcription-profiling_rna-sequencing...
32,OSD-427,48,1,OSD-427_transcription-profiling_rna-sequencing...
36,OSD-437,19,1,OSD-437_transcription-profiling_rna-sequencing...
41,OSD-476,20,2,OSD-476_morphometric-analysis_image-analysis_i...
42,OSD-480,400,1,OSD-480_transcription-profiling_rna-sequencing...
44,OSD-498,16,1,OSD-498_transcription-profiling_rna-sequencing...
45,OSD-502,8,1,OSD-502_transcription-profiling_rna-sequencing...
46,OSD-508,36,1,OSD-508_transcription-profiling_rna-sequencing...
47,OSD-510,48,1,OSD-510_transcription-profiling_rna-sequencing...
48,OSD-518,21,1,OSD-518_transcription-profiling_rna-sequencing...
49,OSD-519,36,1,GLDS-519_transcription-profiling_rna-sequencin...
51,OSD-522,36,2,OSD-522_protein-expression-profiling_mass-spec...
53,OSD-565,45,1,OSD-565_transcription-profiling_rna-sequencing...
55,OSD-624,36,1,OSD-624_transcription-profiling_rna-sequencing...
57,OSD-658,14,1,OSD-658_transcription-profiling_rna-sequencing...
58,OSD-678,36,1,OSD-678_transcription-profiling_rna-sequencing...
60,OSD-782,36,1,OSD-782_transcription-profiling_rna-sequencing...

In [14]:
output_path = "../metadata/arabidopsis_osdr_inventory.csv"

study_inventory.to_csv(output_path, index=False)

print("Guardado en:", output_path)

Guardado en: ../metadata/arabidopsis_osdr_inventory.csv

In [15]:
pd.read_csv(output_path).head()

,id.accession,organism,n_samples,n_assays,assay_names,omics_type
0,OSD-120,Arabidopsis thaliana,90,2,OSD-120_image-analysis_photography_cara | OSD-...,RNA-seq
1,OSD-121,Arabidopsis thaliana,6,3,OSD-121_glycomic-profile_elisa_thermo fisher s...,Microarray
2,OSD-134,Arabidopsis thaliana,33,1,OSD-134_transcription-profiling_dna-microarray...,Microarray
3,OSD-136,Arabidopsis thaliana,9,1,OSD-136_transcription-profiling_dna-microarray...,Microarray
4,OSD-144,Arabidopsis thaliana,24,1,OSD-144_transcription-profiling_dna-microarray...,Microarray

In [16]:
print("Número de estudios únicos:", study_inventory["id.accession"].nunique())

Número de estudios únicos: 62

In [17]:
study_inventory["omics_type"].value_counts()

omics_type
RNA-seq        33
Microarray     22
Other           4
Epigenomics     3
Name: count, dtype: int64

In [18]:
apex_candidates[
    ["id.accession", "omics_type", "n_samples", "assay_names"]
]

,id.accession,omics_type,n_samples,assay_names
1,OSD-121,Microarray,6,OSD-121_glycomic-profile_elisa_thermo fisher s...
12,OSD-217,RNA-seq,24,OSD-217_DNA-methylation-profiling_Whole-Genome...
13,OSD-218,RNA-seq,32,OSD-218_transcription-profiling_rna-sequencing...
28,OSD-38,RNA-seq,36,OSD-38_protein-expression-profiling_mass-spect...
31,OSD-416,Epigenomics,48,OSD-416_dna-methylation-profiling_bisulfite-se...
32,OSD-427,RNA-seq,48,OSD-427_transcription-profiling_rna-sequencing...
54,OSD-615,Other,12,OSD-615_glycomic-profile_elisa_thermo fisher s...
56,OSD-625,Epigenomics,16,OSD-625_targeted-dna-methylation-profiling_ccs...

In [19]:
def contains_any(text, terms):
    text = str(text).lower()
    return any(term.lower() in text for term in terms)


study_inventory["has_rna_seq"] = study_inventory["assay_names"].apply(
    lambda x: contains_any(
        x,
        [
            "rna-sequencing",
            "rna sequencing",
            "rna-seq",
            "transcription-profiling_rna"
        ]
    )
)

study_inventory["has_small_rna"] = study_inventory["assay_names"].apply(
    lambda x: contains_any(
        x,
        [
            "small rna",
            "small-rna",
            "mirna",
            "microRNA"
        ]
    )
)

study_inventory["has_microarray"] = study_inventory["assay_names"].apply(
    lambda x: contains_any(
        x,
        [
            "microarray",
            "dna-microarray"
        ]
    )
)

study_inventory["has_methylation"] = study_inventory["assay_names"].apply(
    lambda x: contains_any(
        x,
        [
            "methylation",
            "bisulfite"
        ]
    )
)

study_inventory["has_proteomics"] = study_inventory["assay_names"].apply(
    lambda x: contains_any(
        x,
        [
            "protein-expression",
            "proteom",
            "mass-spectrometry"
        ]
    )
)

study_inventory["has_metabolomics"] = study_inventory["assay_names"].apply(
    lambda x: contains_any(
        x,
        [
            "metabolom"
        ]
    )
)

study_inventory["has_glycomics"] = study_inventory["assay_names"].apply(
    lambda x: contains_any(
        x,
        [
            "glycomic",
            "glycome",
            "elisa"
        ]
    )
)

In [20]:
omics_summary = pd.Series({
    "RNA-seq": study_inventory["has_rna_seq"].sum(),
    "Small RNA": study_inventory["has_small_rna"].sum(),
    "Microarray": study_inventory["has_microarray"].sum(),
    "Methylation": study_inventory["has_methylation"].sum(),
    "Proteomics": study_inventory["has_proteomics"].sum(),
    "Metabolomics": study_inventory["has_metabolomics"].sum(),
    "Glycomics": study_inventory["has_glycomics"].sum()
})

omics_summary.sort_values(ascending=False)

RNA-seq         33
Microarray      23
Methylation      4
Proteomics       3
Glycomics        2
Small RNA        0
Metabolomics     0
dtype: int64

In [21]:
priority_ids = [
    "OSD-121",
    "OSD-217",
    "OSD-218",
    "OSD-38",
    "OSD-416",
    "OSD-427",
    "OSD-615",
    "OSD-625"
]

priority = study_inventory[
    study_inventory["id.accession"].isin(priority_ids)
].copy()

priority[
    [
        "id.accession",
        "n_samples",
        "has_rna_seq",
        "has_small_rna",
        "has_microarray",
        "has_methylation",
        "has_proteomics",
        "has_metabolomics",
        "has_glycomics"
    ]
].sort_values("id.accession")

,id.accession,n_samples,has_rna_seq,has_small_rna,has_microarray,has_methylation,has_proteomics,has_metabolomics,has_glycomics
1,OSD-121,6,False,False,True,False,False,False,True
12,OSD-217,24,True,False,False,True,False,False,False
13,OSD-218,32,True,False,False,False,False,False,False
28,OSD-38,36,True,False,False,False,True,False,False
31,OSD-416,48,False,False,False,True,False,False,False
32,OSD-427,48,True,False,False,False,False,False,False
54,OSD-615,12,False,False,False,False,False,False,True
56,OSD-625,16,False,False,False,True,False,False,False

In [22]:
pd.set_option("display.max_colwidth", None)

priority[
    ["id.accession", "assay_names"]
].sort_values("id.accession")

,id.accession,assay_names
1,OSD-121,OSD-121_glycomic-profile_elisa_thermo fisher scientific | OSD-121_morphometric-analysis_image-analysis_photography | OSD-121_transcription-profiling_dna-microarray_affymetrix
12,OSD-217,OSD-217_DNA-methylation-profiling_Whole-Genome-Bisulfite-Sequencing_Illumina | OSD-217_transcription-profiling_rna-sequencing-(rna-seq)_illumina
13,OSD-218,OSD-218_transcription-profiling_rna-sequencing-(rna-seq)_illumina
28,OSD-38,OSD-38_protein-expression-profiling_mass-spectrometry_LTQ-Orbitrap Velos Pro | OSD-38_transcription-profiling_rna-sequencing-(rna-seq)_Illumina
31,OSD-416,OSD-416_dna-methylation-profiling_bisulfite-sequencing_Illumina
32,OSD-427,OSD-427_transcription-profiling_rna-sequencing-(rna-seq)_Illumina
54,OSD-615,OSD-615_glycomic-profile_elisa_thermo fisher scientific
56,OSD-625,OSD-625_targeted-dna-methylation-profiling_ccs-long-read-dna-enzymatic-methyl-sequencing_pacific biosciences

In [23]:
small_rna_candidates = study_inventory[
    study_inventory["has_small_rna"]
].copy()

print("Estudios con indicios de small RNA / miRNA:",
      len(small_rna_candidates))

small_rna_candidates[
    ["id.accession", "n_samples", "assay_names"]
]

Estudios con indicios de small RNA / miRNA: 0

Empty DataFrame
Columns: [id.accession, n_samples, assay_names]
Index: []

In [24]:
output_path = "../metadata/arabidopsis_osdr_inventory.csv"

study_inventory.to_csv(
    output_path,
    index=False
)

print(
    f"Inventario guardado: {output_path}\n"
    f"Estudios: {len(study_inventory)}"
)

Inventario guardado: ../metadata/arabidopsis_osdr_inventory.csv
Estudios: 62

In [25]:
pd.read_csv(output_path).head()

,id.accession,organism,n_samples,n_assays,assay_names,omics_type,has_rna_seq,has_small_rna,has_microarray,has_methylation,has_proteomics,has_metabolomics,has_glycomics
0,OSD-120,Arabidopsis thaliana,90,2,OSD-120_image-analysis_photography_cara | OSD-120_transcription-profiling_rna-sequencing-(rna-seq)_illumina,RNA-seq,True,False,False,False,False,False,False
1,OSD-121,Arabidopsis thaliana,6,3,OSD-121_glycomic-profile_elisa_thermo fisher scientific | OSD-121_morphometric-analysis_image-analysis_photography | OSD-121_transcription-profiling_dna-microarray_affymetrix,Microarray,False,False,True,False,False,False,True
2,OSD-134,Arabidopsis thaliana,33,1,OSD-134_transcription-profiling_dna-microarray_affymetrix,Microarray,False,False,True,False,False,False,False
3,OSD-136,Arabidopsis thaliana,9,1,OSD-136_transcription-profiling_dna-microarray_Affymetrix,Microarray,False,False,True,False,False,False,False
4,OSD-144,Arabidopsis thaliana,24,1,OSD-144_transcription-profiling_dna-microarray_Nimblegen,Microarray,False,False,True,False,False,False,False

In [26]:
omics_summary.sort_values(ascending=False)

RNA-seq         33
Microarray      23
Methylation      4
Proteomics       3
Glycomics        2
Small RNA        0
Metabolomics     0
dtype: int64

In [27]:
small_rna_candidates

Empty DataFrame
Columns: [id.accession, organism, n_samples, n_assays, assay_names, omics_type, has_rna_seq, has_small_rna, has_microarray, has_methylation, has_proteomics, has_metabolomics, has_glycomics]
Index: []

In [29]:
detail_url = "https://visualization.osdr.nasa.gov/biodata/api/v2/query/metadata/"

params_detail = {
    "id.accession": "OSD-218",
    "study.factor value": "",
    "study.characteristics": "",
    "study.parameter value": ""
}

r218 = requests.get(detail_url, params=params_detail, timeout=60)

print("Status:", r218.status_code)
print(r218.text[:3000])

Status: 200
id.accession,id.assay name,id.sample name,study.characteristics.developmental stage,study.characteristics.genotype,study.characteristics.organism,study.characteristics.organism part,study.characteristics.seed source,study.factor value.age,study.factor value.cultivar,study.factor value.spaceflight,study.parameter value.growth environment,study.parameter value.growth medium,study.parameter value.growth time,study.parameter value.hardware,study.parameter value.light cycle,study.parameter value.light intensity,study.parameter value.light quality,study.parameter value.light source,study.parameter value.mean growth temperature,study.parameter value.sample preservation method,study.parameter value.sample storage temperature
"OSD-218","OSD-218_transcription-profiling_rna-sequencing-(rna-seq)_illumina","SAMN06465142","Seedlings","Wild Type","Arabidopsis thaliana","root","Not Available","8 {day}","Col-0","Space Flight","ISS","0.5% Phytagel 0.5x MS media","8 {day}","Vegetable Production System (Veggie)","Not Available","100-135 {micromole per square meter per second}","Not Available","Light Emitting Diode Device","15.687 {degree Celsius}","RNALater","-80 {degree Celsius}"
"OSD-218","OSD-218_transcription-profiling_rna-sequencing-(rna-seq)_illumina","SAMN06465144","Seedlings","Wild Type","Arabidopsis thaliana","root","Not Available","8 {day}","Col-0","Space Flight","ISS","0.5% Phytagel 0.5x MS media","8 {day}","Vegetable Production System (Veggie)","Not Available","100-135 {micromole per square meter per second}","Not Available","Light Emitting Diode Device","15.687 {degree Celsius}","RNALater","-80 {degree Celsius}"
"OSD-218","OSD-218_transcription-profiling_rna-sequencing-(rna-seq)_illumina","SAMN06465146","Seedlings","Wild Type","Arabidopsis thaliana","root","Not Available","8 {day}","Col-0","Space Flight","ISS","0.5% Phytagel 0.5x MS media","8 {day}","Vegetable Production System (Veggie)","Not Available","100-135 {micromole per square meter per second}","Not Available","Light Emitting Diode Device","15.687 {degree Celsius}","RNALater","-80 {degree Celsius}"
"OSD-218","OSD-218_transcription-profiling_rna-sequencing-(rna-seq)_illumina","SAMN06465148","Seedlings","Wild Type","Arabidopsis thaliana","root","Not Available","8 {day}","Col-0","Space Flight","ISS","0.5% Phytagel 0.5x MS media","8 {day}","Vegetable Production System (Veggie)","Not Available","100-135 {micromole per square meter per second}","Not Available","Light Emitting Diode Device","15.687 {degree Celsius}","RNALater","-80 {degree Celsius}"
"OSD-218","OSD-218_transcription-profiling_rna-sequencing-(rna-seq)_illumina","SAMN06465150","Seedlings","Wild Type","Arabidopsis thaliana","root","Not Available","8 {day}","Col-0","Ground Control","ISSES","0.5% Phytagel 0.5x MS media","8 {day}","Vegetable Production System (Veggie)","Not Available","100-135 {micromole per square meter per second}","Not Available","Light Emitting Diode Device","14.655 {degree Celsius}","RNALater","-80 {degree Celsius}"

In [30]:
df218 = pd.read_csv(StringIO(r218.text))

print("Filas:", len(df218))
print("Columnas:", len(df218.columns))

df218.columns.tolist()

Filas: 32
Columnas: 22

['id.accession',
 'id.assay name',
 'id.sample name',
 'study.characteristics.developmental stage',
 'study.characteristics.genotype',
 'study.characteristics.organism',
 'study.characteristics.organism part',
 'study.characteristics.seed source',
 'study.factor value.age',
 'study.factor value.cultivar',
 'study.factor value.spaceflight',
 'study.parameter value.growth environment',
 'study.parameter value.growth medium',
 'study.parameter value.growth time',
 'study.parameter value.hardware',
 'study.parameter value.light cycle',
 'study.parameter value.light intensity',
 'study.parameter value.light quality',
 'study.parameter value.light source',
 'study.parameter value.mean growth temperature',
 'study.parameter value.sample preservation method',
 'study.parameter value.sample storage temperature']

In [31]:
df218.head()

,id.accession,id.assay name,id.sample name,study.characteristics.developmental stage,study.characteristics.genotype,study.characteristics.organism,study.characteristics.organism part,study.characteristics.seed source,study.factor value.age,study.factor value.cultivar,...,study.parameter value.growth medium,study.parameter value.growth time,study.parameter value.hardware,study.parameter value.light cycle,study.parameter value.light intensity,study.parameter value.light quality,study.parameter value.light source,study.parameter value.mean growth temperature,study.parameter value.sample preservation method,study.parameter value.sample storage temperature
0,OSD-218,OSD-218_transcription-profiling_rna-sequencing-(rna-seq)_illumina,SAMN06465142,Seedlings,Wild Type,Arabidopsis thaliana,root,Not Available,8 {day},Col-0,...,0.5% Phytagel 0.5x MS media,8 {day},Vegetable Production System (Veggie),Not Available,100-135 {micromole per square meter per second},Not Available,Light Emitting Diode Device,15.687 {degree Celsius},RNALater,-80 {degree Celsius}
1,OSD-218,OSD-218_transcription-profiling_rna-sequencing-(rna-seq)_illumina,SAMN06465144,Seedlings,Wild Type,Arabidopsis thaliana,root,Not Available,8 {day},Col-0,...,0.5% Phytagel 0.5x MS media,8 {day},Vegetable Production System (Veggie),Not Available,100-135 {micromole per square meter per second},Not Available,Light Emitting Diode Device,15.687 {degree Celsius},RNALater,-80 {degree Celsius}
2,OSD-218,OSD-218_transcription-profiling_rna-sequencing-(rna-seq)_illumina,SAMN06465146,Seedlings,Wild Type,Arabidopsis thaliana,root,Not Available,8 {day},Col-0,...,0.5% Phytagel 0.5x MS media,8 {day},Vegetable Production System (Veggie),Not Available,100-135 {micromole per square meter per second},Not Available,Light Emitting Diode Device,15.687 {degree Celsius},RNALater,-80 {degree Celsius}
3,OSD-218,OSD-218_transcription-profiling_rna-sequencing-(rna-seq)_illumina,SAMN06465148,Seedlings,Wild Type,Arabidopsis thaliana,root,Not Available,8 {day},Col-0,...,0.5% Phytagel 0.5x MS media,8 {day},Vegetable Production System (Veggie),Not Available,100-135 {micromole per square meter per second},Not Available,Light Emitting Diode Device,15.687 {degree Celsius},RNALater,-80 {degree Celsius}
4,OSD-218,OSD-218_transcription-profiling_rna-sequencing-(rna-seq)_illumina,SAMN06465150,Seedlings,Wild Type,Arabidopsis thaliana,root,Not Available,8 {day},Col-0,...,0.5% Phytagel 0.5x MS media,8 {day},Vegetable Production System (Veggie),Not Available,100-135 {micromole per square meter per second},Not Available,Light Emitting Diode Device,14.655 {degree Celsius},RNALater,-80 {degree Celsius}

In [32]:
for col in df218.columns:
    print(col)

id.accession
id.assay name
id.sample name
study.characteristics.developmental stage
study.characteristics.genotype
study.characteristics.organism
study.characteristics.organism part
study.characteristics.seed source
study.factor value.age
study.factor value.cultivar
study.factor value.spaceflight
study.parameter value.growth environment
study.parameter value.growth medium
study.parameter value.growth time
study.parameter value.hardware
study.parameter value.light cycle
study.parameter value.light intensity
study.parameter value.light quality
study.parameter value.light source
study.parameter value.mean growth temperature
study.parameter value.sample preservation method
study.parameter value.sample storage temperature

In [33]:
df218.columns.tolist()

['id.accession',
 'id.assay name',
 'id.sample name',
 'study.characteristics.developmental stage',
 'study.characteristics.genotype',
 'study.characteristics.organism',
 'study.characteristics.organism part',
 'study.characteristics.seed source',
 'study.factor value.age',
 'study.factor value.cultivar',
 'study.factor value.spaceflight',
 'study.parameter value.growth environment',
 'study.parameter value.growth medium',
 'study.parameter value.growth time',
 'study.parameter value.hardware',
 'study.parameter value.light cycle',
 'study.parameter value.light intensity',
 'study.parameter value.light quality',
 'study.parameter value.light source',
 'study.parameter value.mean growth temperature',
 'study.parameter value.sample preservation method',
 'study.parameter value.sample storage temperature']

In [34]:
cols_main = [
    "id.sample name",
    "study.factor value.spaceflight",
    "study.factor value.age",
    "study.factor value.cultivar",
    "study.characteristics.genotype",
    "study.characteristics.organism part",
    "study.characteristics.developmental stage",
    "study.parameter value.growth environment",
    "study.parameter value.growth time",
    "study.parameter value.hardware",
    "study.parameter value.light cycle",
    "study.parameter value.light intensity",
    "study.parameter value.light quality",
    "study.parameter value.light source",
    "study.parameter value.mean growth temperature"
]

meta218 = df218[cols_main].copy()

meta218.head()

,id.sample name,study.factor value.spaceflight,study.factor value.age,study.factor value.cultivar,study.characteristics.genotype,study.characteristics.organism part,study.characteristics.developmental stage,study.parameter value.growth environment,study.parameter value.growth time,study.parameter value.hardware,study.parameter value.light cycle,study.parameter value.light intensity,study.parameter value.light quality,study.parameter value.light source,study.parameter value.mean growth temperature
0,SAMN06465142,Space Flight,8 {day},Col-0,Wild Type,root,Seedlings,ISS,8 {day},Vegetable Production System (Veggie),Not Available,100-135 {micromole per square meter per second},Not Available,Light Emitting Diode Device,15.687 {degree Celsius}
1,SAMN06465144,Space Flight,8 {day},Col-0,Wild Type,root,Seedlings,ISS,8 {day},Vegetable Production System (Veggie),Not Available,100-135 {micromole per square meter per second},Not Available,Light Emitting Diode Device,15.687 {degree Celsius}
2,SAMN06465146,Space Flight,8 {day},Col-0,Wild Type,root,Seedlings,ISS,8 {day},Vegetable Production System (Veggie),Not Available,100-135 {micromole per square meter per second},Not Available,Light Emitting Diode Device,15.687 {degree Celsius}
3,SAMN06465148,Space Flight,8 {day},Col-0,Wild Type,root,Seedlings,ISS,8 {day},Vegetable Production System (Veggie),Not Available,100-135 {micromole per square meter per second},Not Available,Light Emitting Diode Device,15.687 {degree Celsius}
4,SAMN06465150,Ground Control,8 {day},Col-0,Wild Type,root,Seedlings,ISSES,8 {day},Vegetable Production System (Veggie),Not Available,100-135 {micromole per square meter per second},Not Available,Light Emitting Diode Device,14.655 {degree Celsius}

In [35]:
print("Filas:", len(meta218))
print("Muestras únicas:", meta218["id.sample name"].nunique())

Filas: 32
Muestras únicas: 32

In [36]:
for col in cols_main[1:]:
    print("\n" + "=" * 80)
    print(col)

    values = (
        meta218[col]
        .dropna()
        .astype(str)
        .unique()
    )

    for value in values:
        print(" -", value)

================================================================================
study.factor value.spaceflight
 - Space Flight
 - Ground Control

================================================================================
study.factor value.age
 - 8 {day}
 - 4 {day}

================================================================================
study.factor value.cultivar
 - Col-0
 - WS

================================================================================
study.characteristics.genotype
 - Wild Type

================================================================================
study.characteristics.organism part
 - root

================================================================================
study.characteristics.developmental stage
 - Seedlings

================================================================================
study.parameter value.growth environment
 - ISS
 - ISSES

================================================================================
study.parameter value.growth time
 - 8 {day}
 - 4 {day}

================================================================================
study.parameter value.hardware
 - Vegetable Production System (Veggie)

================================================================================
study.parameter value.light cycle
 - Not Available

================================================================================
study.parameter value.light intensity
 - 100-135 {micromole per square meter per second}

================================================================================
study.parameter value.light quality
 - Not Available

================================================================================
study.parameter value.light source
 - Light Emitting Diode Device

================================================================================
study.parameter value.mean growth temperature
 - 15.687 {degree Celsius}
 - 14.655 {degree Celsius}

In [37]:
design_summary = (
    meta218
    .groupby(
        [
            "study.factor value.spaceflight",
            "study.factor value.age",
            "study.factor value.cultivar",
            "study.characteristics.genotype"
        ],
        dropna=False
    )
    .agg(
        n_samples=("id.sample name", "nunique")
    )
    .reset_index()
)

design_summary

,study.factor value.spaceflight,study.factor value.age,study.factor value.cultivar,study.characteristics.genotype,n_samples
0,Ground Control,4 {day},Col-0,Wild Type,4
1,Ground Control,4 {day},WS,Wild Type,4
2,Ground Control,8 {day},Col-0,Wild Type,4
3,Ground Control,8 {day},WS,Wild Type,4
4,Space Flight,4 {day},Col-0,Wild Type,4
5,Space Flight,4 {day},WS,Wild Type,4
6,Space Flight,8 {day},Col-0,Wild Type,4
7,Space Flight,8 {day},WS,Wild Type,4

In [38]:
pd.crosstab(
    meta218["study.factor value.spaceflight"],
    meta218["study.factor value.age"]
)

study.factor value.age          4 {day}  8 {day}
study.factor value.spaceflight
Ground Control                        8        8
Space Flight                          8        8

In [39]:
pd.crosstab(
    meta218["study.factor value.spaceflight"],
    meta218["study.factor value.cultivar"]
)

study.factor value.cultivar     Col-0  WS
study.factor value.spaceflight
Ground Control                      8   8
Space Flight                        8   8

In [40]:
pd.crosstab(
    meta218["study.factor value.spaceflight"],
    meta218["study.characteristics.genotype"]
)

study.characteristics.genotype  Wild Type
study.factor value.spaceflight
Ground Control                         16
Space Flight                           16

In [41]:
light_cols = [
    "study.parameter value.light cycle",
    "study.parameter value.light intensity",
    "study.parameter value.light quality",
    "study.parameter value.light source"
]

light_metadata = meta218[light_cols].drop_duplicates()

light_metadata

,study.parameter value.light cycle,study.parameter value.light intensity,study.parameter value.light quality,study.parameter value.light source
0,Not Available,100-135 {micromole per square meter per second},Not Available,Light Emitting Diode Device

In [42]:
meta218[
    [
        "study.parameter value.hardware",
        "study.parameter value.growth environment",
        "study.parameter value.mean growth temperature"
    ]
].drop_duplicates()

,study.parameter value.hardware,study.parameter value.growth environment,study.parameter value.mean growth temperature
0,Vegetable Production System (Veggie),ISS,15.687 {degree Celsius}
4,Vegetable Production System (Veggie),ISSES,14.655 {degree Celsius}

In [43]:
output_218 = "../metadata/OSD-218_sample_metadata.csv"

meta218.to_csv(
    output_218,
    index=False
)

print("Guardado:", output_218)

Guardado: ../metadata/OSD-218_sample_metadata.csv

In [44]:
design_summary.to_csv(
    "../metadata/OSD-218_design_summary.csv",
    index=False
)

In [45]:
print("Muestras únicas:", meta218["id.sample name"].nunique())

Muestras únicas: 32

In [48]:
def summarize_study(osd_id):
    url = "https://visualization.osdr.nasa.gov/biodata/api/v2/query/metadata/"

    params = {
        "id.accession": osd_id,
        "study.characteristics": "",
        "study.factor value": "",
        "study.parameter value": ""
    }

    r = requests.get(url, params=params, timeout=60)
    r.raise_for_status()

    df_study = pd.read_csv(StringIO(r.text))

    def unique_values(column):
        if column not in df_study.columns:
            return None

        values = (
            df_study[column]
            .dropna()
            .astype(str)
            .unique()
            .tolist()
        )

        return " | ".join(values) if values else None

    return {
        "OSD_ID": osd_id,
        "n_samples": df_study["id.sample name"].nunique()
            if "id.sample name" in df_study.columns else None,

        "spaceflight": unique_values("study.factor value.spaceflight"),
        "age": unique_values("study.factor value.age"),
        "cultivar": unique_values("study.factor value.cultivar"),
        "genotype": unique_values("study.characteristics.genotype"),
        "organ": unique_values("study.characteristics.organism part"),
        "developmental_stage": unique_values(
            "study.characteristics.developmental stage"
        ),

        "growth_environment": unique_values(
            "study.parameter value.growth environment"
        ),

        "hardware": unique_values(
            "study.parameter value.hardware"
        ),

        "light_cycle": unique_values(
            "study.parameter value.light cycle"
        ),

        "light_intensity": unique_values(
            "study.parameter value.light intensity"
        ),

        "light_quality": unique_values(
            "study.parameter value.light quality"
        ),

        "light_source": unique_values(
            "study.parameter value.light source"
        ),

        "temperature": unique_values(
            "study.parameter value.mean growth temperature"
        )
    }

In [47]:
summary_218 = summarize_study("OSD-218")
summary_218

{'OSD_ID': 'OSD-218',
 'n_samples': 32,
 'spaceflight': 'Space Flight | Ground Control',
 'age': '8 {day} | 4 {day}',
 'cultivar': 'Col-0 | WS',
 'genotype': 'Wild Type',
 'organ': 'root',
 'developmental_stage': 'Seedlings',
 'growth_environment': 'ISS | ISSES',
 'hardware': 'Vegetable Production System (Veggie)',
 'light_cycle': 'Not Available',
 'light_intensity': '100-135 {micromole per square meter per second}',
 'light_quality': 'Not Available',
 'light_source': 'Light Emitting Diode Device',
 'temperature': '15.687 {degree Celsius} | 14.655 {degree Celsius}'}

In [49]:
pd.DataFrame([summary_218])

,OSD_ID,n_samples,spaceflight,age,cultivar,genotype,organ,developmental_stage,growth_environment,hardware,light_cycle,light_intensity,light_quality,light_source,temperature
0,OSD-218,32,Space Flight | Ground Control,8 {day} | 4 {day},Col-0 | WS,Wild Type,root,Seedlings,ISS | ISSES,Vegetable Production System (Veggie),Not Available,100-135 {micromole per square meter per second},Not Available,Light Emitting Diode Device,15.687 {degree Celsius} | 14.655 {degree Celsius}

In [50]:
from time import sleep

all_summaries = []
errors = []

osd_ids = study_inventory["id.accession"].tolist()

for i, osd_id in enumerate(osd_ids, start=1):
    print(f"[{i}/{len(osd_ids)}] Procesando {osd_id}...")

    try:
        summary = summarize_study(osd_id)
        all_summaries.append(summary)

    except Exception as e:
        errors.append({
            "OSD_ID": osd_id,
            "error": str(e)
        })

        print(f"  Error en {osd_id}: {e}")

    sleep(0.2)

[1/62] Procesando OSD-120...
[2/62] Procesando OSD-121...
[3/62] Procesando OSD-134...
[4/62] Procesando OSD-136...
[5/62] Procesando OSD-144...
[6/62] Procesando OSD-147...
[7/62] Procesando OSD-16...
[8/62] Procesando OSD-17...
[9/62] Procesando OSD-193...
[10/62] Procesando OSD-205...
[11/62] Procesando OSD-208...
[12/62] Procesando OSD-210...
[13/62] Procesando OSD-217...
[14/62] Procesando OSD-218...
[15/62] Procesando OSD-219...
[16/62] Procesando OSD-22...
[17/62] Procesando OSD-223...
[18/62] Procesando OSD-251...
[19/62] Procesando OSD-281...
[20/62] Procesando OSD-282...
[21/62] Procesando OSD-296...
[22/62] Procesando OSD-313...
[23/62] Procesando OSD-314...
[24/62] Procesando OSD-320...
[25/62] Procesando OSD-321...
[26/62] Procesando OSD-329...
[27/62] Procesando OSD-346...
[28/62] Procesando OSD-37...
[29/62] Procesando OSD-38...
[30/62] Procesando OSD-406...
[31/62] Procesando OSD-411...
[32/62] Procesando OSD-416...
[33/62] Procesando OSD-427...
[34/62] Procesando OSD-428...
[35/62] Procesando OSD-434...
[36/62] Procesando OSD-436...
[37/62] Procesando OSD-437...
[38/62] Procesando OSD-44...
[39/62] Procesando OSD-45...
[40/62] Procesando OSD-450...
[41/62] Procesando OSD-46...
[42/62] Procesando OSD-476...
[43/62] Procesando OSD-480...
[44/62] Procesando OSD-496...
[45/62] Procesando OSD-498...
[46/62] Procesando OSD-502...
[47/62] Procesando OSD-508...
[48/62] Procesando OSD-510...
[49/62] Procesando OSD-518...
[50/62] Procesando OSD-519...
[51/62] Procesando OSD-520...
[52/62] Procesando OSD-522...
[53/62] Procesando OSD-531...
[54/62] Procesando OSD-565...
[55/62] Procesando OSD-615...
[56/62] Procesando OSD-624...
[57/62] Procesando OSD-625...
[58/62] Procesando OSD-658...
[59/62] Procesando OSD-678...
[60/62] Procesando OSD-7...
[61/62] Procesando OSD-782...
[62/62] Procesando OSD-8...

In [51]:
metadata_summary = pd.DataFrame(all_summaries)

print("Estudios procesados:", len(metadata_summary))
print("Errores:", len(errors))

metadata_summary.head()

Estudios procesados: 62
Errores: 0

,OSD_ID,n_samples,spaceflight,age,cultivar,genotype,organ,developmental_stage,growth_environment,hardware,light_cycle,light_intensity,light_quality,light_source,temperature
0,OSD-120,90,Space Flight | Ground Control,NaN,NaN,NaN,Plant Roots,NaN,ISS-Columbus | Earth surface,petri dish,NaN,NaN,NaN,ambient light | Not Applicable,NaN
1,OSD-121,6,Space Flight | Ground Control,NaN,NaN,NaN,Plant Shoots,NaN,Space Shuttle | Earth surface,BRIC-PDFU | Orbital Environmental Simulator (OES),24 dark {hour},NaN,NaN,NaN,24 {degree Celsius}
2,OSD-134,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Low Pressure Growth Chambers (LPGC),24 light {hour},70-80 {micromole per square meter per second},NaN,NaN,23 {degree Celsius}
3,OSD-136,9,NaN,NaN,NaN,NaN,Plant Roots,NaN,NaN,NaN,24 light hour,NaN,NaN,NaN,NaN
4,OSD-144,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
pd.DataFrame(errors)

Empty DataFrame
Columns: []
Index: []

In [53]:
full_inventory = study_inventory.merge(
    metadata_summary,
    left_on="id.accession",
    right_on="OSD_ID",
    how="left"
)

full_inventory.head()

,id.accession,organism,n_samples_x,n_assays,assay_names,omics_type,has_rna_seq,has_small_rna,has_microarray,has_methylation,...,genotype,organ,developmental_stage,growth_environment,hardware,light_cycle,light_intensity,light_quality,light_source,temperature
0,OSD-120,Arabidopsis thaliana,90,2,OSD-120_image-analysis_photography_cara | OSD-120_transcription-profiling_rna-sequencing-(rna-seq)_illumina,RNA-seq,True,False,False,False,...,NaN,Plant Roots,NaN,ISS-Columbus | Earth surface,petri dish,NaN,NaN,NaN,ambient light | Not Applicable,NaN
1,OSD-121,Arabidopsis thaliana,6,3,OSD-121_glycomic-profile_elisa_thermo fisher scientific | OSD-121_morphometric-analysis_image-analysis_photography | OSD-121_transcription-profiling_dna-microarray_affymetrix,Microarray,False,False,True,False,...,NaN,Plant Shoots,NaN,Space Shuttle | Earth surface,BRIC-PDFU | Orbital Environmental Simulator (OES),24 dark {hour},NaN,NaN,NaN,24 {degree Celsius}
2,OSD-134,Arabidopsis thaliana,33,1,OSD-134_transcription-profiling_dna-microarray_affymetrix,Microarray,False,False,True,False,...,NaN,NaN,NaN,NaN,Low Pressure Growth Chambers (LPGC),24 light {hour},70-80 {micromole per square meter per second},NaN,NaN,23 {degree Celsius}
3,OSD-136,Arabidopsis thaliana,9,1,OSD-136_transcription-profiling_dna-microarray_Affymetrix,Microarray,False,False,True,False,...,NaN,Plant Roots,NaN,NaN,NaN,24 light hour,NaN,NaN,NaN,NaN
4,OSD-144,Arabidopsis thaliana,24,1,OSD-144_transcription-profiling_dna-microarray_Nimblegen,Microarray,False,False,True,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
output_full = "../metadata/arabidopsis_osdr_inventory_enriched.csv"

full_inventory.to_csv(
    output_full,
    index=False
)

print("Guardado:", output_full)

Guardado: ../metadata/arabidopsis_osdr_inventory_enriched.csv

In [55]:
candidate_rnaseq = full_inventory[
    (full_inventory["has_rna_seq"] == True) &
    (full_inventory["spaceflight"].fillna("").str.contains("Space Flight")) &
    (full_inventory["spaceflight"].fillna("").str.contains("Ground Control"))
].copy()

print("RNA-seq con Flight y Ground Control:", len(candidate_rnaseq))

RNA-seq con Flight y Ground Control: 15

In [56]:
candidate_rnaseq[
    [
        "id.accession",
        "n_samples_x",
        "age",
        "cultivar",
        "genotype",
        "organ",
        "hardware",
        "light_intensity"
    ]
].sort_values("id.accession")

,id.accession,n_samples_x,age,cultivar,genotype,organ,hardware,light_intensity
0,OSD-120,90,NaN,NaN,NaN,Plant Roots,petri dish,NaN
8,OSD-193,32,NaN,NaN,NaN,Plant Roots,Vegetable Production System (Veggie),100-135 {micromole per square meter per second}
12,OSD-217,24,NaN,NaN,NaN,NaN,Vegetable Production System (Veggie),100-135 {micromoles/m^2/s}
13,OSD-218,32,8 {day} | 4 {day},Col-0 | WS,Wild Type,root,Vegetable Production System (Veggie),100-135 {micromole per square meter per second}
14,OSD-219,32,8 {day} | 4 {day},Col-0 | WS,Wild-type,NaN,VPS/Veggie,NaN
16,OSD-223,40,NaN,NaN,NaN,NaN,"European Modular Cultivation System (EMCS) | NASA Ames, Experimental Reference Module (ERM2)",NaN
18,OSD-281,32,8 {day} | 4 {day},NaN,NaN,Plant Roots,Vegetable Production System (Veggie),100-135 {Î¼moles/m2/s PAR}
22,OSD-314,17,NaN,NaN,Wild Type,NaN,European Modular Cultivation System (EMCS),NaN
24,OSD-321,44,NaN,NaN,NaN,NaN,BRIC-PDFU (Petri Dish Fixation Unit),NaN
27,OSD-37,56,NaN,NaN,Wild Type,NaN,BRIC-PDFU (Petri Dish Fixation Unit),NaN
28,OSD-38,36,NaN,NaN,Wild Type,Seedlings,BRIC-PDFU,Not applicable
32,OSD-427,48,NaN,NaN,NaN,NaN,Vegetable Production System (Veggie),100-135 {micromole per square meter per second}
36,OSD-437,19,4 {day} | 6 {day},NaN,Col-0,shoot,"European Modular Cultivation System (EMCS) | NASA Ames, Experimental Reference Module (ERM2)",NaN
51,OSD-522,36,NaN,NaN,NaN,NaN,NaN,60 {micromole per square meter per second}
58,OSD-678,36,NaN,NaN,NaN,Plant Leaves,Petri Dish,{Not Applicable} | 4â6 {micromole per square meter per second}

In [57]:
full_inventory = full_inventory.rename(
    columns={
        "n_samples_x": "n_samples_inventory",
        "n_samples_y": "n_samples_metadata"
    }
)

In [58]:
rnaseq_candidates = full_inventory[
    (full_inventory["has_rna_seq"] == True) &
    (full_inventory["spaceflight"].fillna("").str.contains("Space Flight")) &
    (full_inventory["spaceflight"].fillna("").str.contains("Ground Control"))
].copy()

candidate_table = rnaseq_candidates[
    [
        "id.accession",
        "n_samples_inventory",
        "age",
        "cultivar",
        "genotype",
        "organ",
        "developmental_stage",
        "growth_environment",
        "hardware",
        "light_cycle",
        "light_intensity",
        "light_quality",
        "light_source",
        "temperature",
        "assay_names"
    ]
].sort_values("id.accession")

candidate_table

,id.accession,n_samples_inventory,age,cultivar,genotype,organ,developmental_stage,growth_environment,hardware,light_cycle,light_intensity,light_quality,light_source,temperature,assay_names
0,OSD-120,90,NaN,NaN,NaN,Plant Roots,NaN,ISS-Columbus | Earth surface,petri dish,NaN,NaN,NaN,ambient light | Not Applicable,NaN,OSD-120_image-analysis_photography_cara | OSD-120_transcription-profiling_rna-sequencing-(rna-seq)_illumina
8,OSD-193,32,NaN,NaN,NaN,Plant Roots,NaN,International Space Station Environmental Simulator (ISSES) | ISS-Columbus,Vegetable Production System (Veggie),NaN,100-135 {micromole per square meter per second},NaN,Light Emitting Diode Device,NaN,OSD-193_transcription-profiling_rna-sequencing-(rna-seq)_Illumina
12,OSD-217,24,NaN,NaN,NaN,NaN,NaN,ISSES | ISS,Vegetable Production System (Veggie),NaN,100-135 {micromoles/m^2/s},NaN,light-emitting diode,NaN,OSD-217_DNA-methylation-profiling_Whole-Genome-Bisulfite-Sequencing_Illumina | OSD-217_transcription-profiling_rna-sequencing-(rna-seq)_illumina
13,OSD-218,32,8 {day} | 4 {day},Col-0 | WS,Wild Type,root,Seedlings,ISS | ISSES,Vegetable Production System (Veggie),Not Available,100-135 {micromole per square meter per second},Not Available,Light Emitting Diode Device,15.687 {degree Celsius} | 14.655 {degree Celsius},OSD-218_transcription-profiling_rna-sequencing-(rna-seq)_illumina
14,OSD-219,32,8 {day} | 4 {day},Col-0 | WS,Wild-type,NaN,NaN,NaN,VPS/Veggie,NaN,NaN,NaN,NaN,NaN,gse95373_transcription_profiling_RNA_Sequencing_(RNA-Seq)
16,OSD-223,40,NaN,NaN,NaN,NaN,NaN,ISS-Columbus | Earth surface,"European Modular Cultivation System (EMCS) | NASA Ames, Experimental Reference Module (ERM2)",24 light {hour},NaN,NaN,Light Emitting Diode Device,24 {degree Celsius},OSD-223_transcription-profiling_rna-sequencing-(rna-seq)_illumina
18,OSD-281,32,8 {day} | 4 {day},NaN,NaN,Plant Roots,Seedlings,NaN,Vegetable Production System (Veggie),NaN,100-135 {Î¼moles/m2/s PAR},NaN,Light Emitting Diode Device,NaN,OSD-281_transcription-profiling_rna-sequencing-(rna-seq)_Illumina
22,OSD-314,17,NaN,NaN,Wild Type,NaN,NaN,ISS-Columbus | Earth surface,European Modular Cultivation System (EMCS),NaN,NaN,NaN,NaN,22.5 {degree Celsius},OSD-314_transcription-profiling_rna-sequencing-(rna-seq)_Illumina
24,OSD-321,44,NaN,NaN,NaN,NaN,NaN,ISS-US Laboratory | ISS Environmental Simulator,BRIC-PDFU (Petri Dish Fixation Unit),24 dark {hour},NaN,NaN,NaN,NaN,OSD-321_transcription-profiling_rna-sequencing-(rna-seq)
27,OSD-37,56,NaN,NaN,Wild Type,NaN,NaN,ISS-US Laboratory,BRIC-PDFU (Petri Dish Fixation Unit),dark 24 {hour},NaN,NaN,continuous dark (no light) regimen,NaN,OSD-37_transcription-profiling_rna-sequencing-(rna-seq)_Illumina
28,OSD-38,36,NaN,NaN,Wild Type,Seedlings,NaN,NaN,BRIC-PDFU,Dark 24 {hour},Not applicable,Not applicable,continuous dark (no light) regimen,NaN,OSD-38_protein-expression-profiling_mass-spectrometry_LTQ-Orbitrap Velos Pro | OSD-38_transcription-profiling_rna-sequencing-(rna-seq)_Illumina
32,OSD-427,48,NaN,NaN,NaN,NaN,NaN,ISS-Columbus | Earth surface,Vegetable Production System (Veggie),24 light {hour},100-135 {micromole per square meter per second},NaN,Light Emitting Diode Device,19.06 {degree Celsius},OSD-427_transcription-profiling_rna-sequencing-(rna-seq)_Illumina
36,OSD-437,19,4 {day} | 6 {day},NaN,Col-0,shoot,NaN,ISS-Columbus | Earth surface,"European Modular Cultivation System (EMCS) | NASA Ames, Experimental Reference Module (ERM2)",16:8 light:dark {hour},NaN,NaN,Light Emitting Diode Device,22 {degree Celsius},OSD-437_transcription-profiling_rna-sequencing-(rna-seq)_Illumina
51,OSD-522,36,NaN,NaN,NaN,NaN,2 rosette leaves are greater than 1 mm in length,International Space Station | International Space Station Environmental Simulator (ISSES),NaN,4:2 light:dark {hour},60 {micromole per square meter per second},NaN,NaN,23 {degree Celsius},OSD-522_protein-expression-profiling_mass-spectrometry_ltq orbitrap velos(thermo scientific) | OSD-522_transcription-profiling_rna-sequencing-(rna-seq)_illumina
58,OSD-678,36,NaN,NaN,NaN,Plant Leaves,NaN,ISS-US Laboratory | International Space Station Environmental Simulator (ISSES),Petri Dish,24 hr Dark | 24 hr Light,{Not Applicable} | 4â6 {micromole per square meter per second},NaN,Not Applicable | ambient light,NaN,OSD-678_transcription-profiling_rna-sequencing-(rna-seq)_illumina

In [59]:
candidate_table.to_csv(
    "../metadata/arabidopsis_spaceflight_rnaseq_candidates.csv",
    index=False
)

print("Candidatos guardados:", len(candidate_table))

Candidatos guardados: 15

In [60]:
candidate_table[
    [
        "id.accession",
        "n_samples_inventory",
        "age",
        "cultivar",
        "organ",
        "hardware"
    ]
]

,id.accession,n_samples_inventory,age,cultivar,organ,hardware
0,OSD-120,90,NaN,NaN,Plant Roots,petri dish
8,OSD-193,32,NaN,NaN,Plant Roots,Vegetable Production System (Veggie)
12,OSD-217,24,NaN,NaN,NaN,Vegetable Production System (Veggie)
13,OSD-218,32,8 {day} | 4 {day},Col-0 | WS,root,Vegetable Production System (Veggie)
14,OSD-219,32,8 {day} | 4 {day},Col-0 | WS,NaN,VPS/Veggie
16,OSD-223,40,NaN,NaN,NaN,"European Modular Cultivation System (EMCS) | NASA Ames, Experimental Reference Module (ERM2)"
18,OSD-281,32,8 {day} | 4 {day},NaN,Plant Roots,Vegetable Production System (Veggie)
22,OSD-314,17,NaN,NaN,NaN,European Modular Cultivation System (EMCS)
24,OSD-321,44,NaN,NaN,NaN,BRIC-PDFU (Petri Dish Fixation Unit)
27,OSD-37,56,NaN,NaN,NaN,BRIC-PDFU (Petri Dish Fixation Unit)
28,OSD-38,36,NaN,NaN,Seedlings,BRIC-PDFU
32,OSD-427,48,NaN,NaN,NaN,Vegetable Production System (Veggie)
36,OSD-437,19,4 {day} | 6 {day},NaN,shoot,"European Modular Cultivation System (EMCS) | NASA Ames, Experimental Reference Module (ERM2)"
51,OSD-522,36,NaN,NaN,NaN,NaN
58,OSD-678,36,NaN,NaN,Plant Leaves,Petri Dish

In [61]:
for _, row in candidate_table.iterrows():

    print("\n" + "=" * 80)
    print(row["id.accession"])

    print("Samples:", row["n_samples_inventory"])
    print("Age:", row["age"])
    print("Cultivar:", row["cultivar"])
    print("Genotype:", row["genotype"])
    print("Organ:", row["organ"])
    print("Hardware:", row["hardware"])

================================================================================
OSD-120
Samples: 90
Age: nan
Cultivar: nan
Genotype: nan
Organ: Plant Roots
Hardware: petri dish

================================================================================
OSD-193
Samples: 32
Age: nan
Cultivar: nan
Genotype: nan
Organ: Plant Roots
Hardware: Vegetable Production System (Veggie)

================================================================================
OSD-217
Samples: 24
Age: nan
Cultivar: nan
Genotype: nan
Organ: nan
Hardware: Vegetable Production System (Veggie)

================================================================================
OSD-218
Samples: 32
Age: 8 {day} | 4 {day}
Cultivar: Col-0 | WS
Genotype: Wild Type
Organ: root
Hardware: Vegetable Production System (Veggie)

================================================================================
OSD-219
Samples: 32
Age: 8 {day} | 4 {day}
Cultivar: Col-0 | WS
Genotype: Wild-type
Organ: nan
Hardware: VPS/Veggie

================================================================================
OSD-223
Samples: 40
Age: nan
Cultivar: nan
Genotype: nan
Organ: nan
Hardware: European Modular Cultivation System (EMCS) | NASA Ames, Experimental Reference Module (ERM2)

================================================================================
OSD-281
Samples: 32
Age: 8 {day} | 4 {day}
Cultivar: nan
Genotype: nan
Organ: Plant Roots
Hardware: Vegetable Production System (Veggie)

================================================================================
OSD-314
Samples: 17
Age: nan
Cultivar: nan
Genotype: Wild Type
Organ: nan
Hardware: European Modular Cultivation System (EMCS)

================================================================================
OSD-321
Samples: 44
Age: nan
Cultivar: nan
Genotype: nan
Organ: nan
Hardware: BRIC-PDFU (Petri Dish Fixation Unit)

================================================================================
OSD-37
Samples: 56
Age: nan
Cultivar: nan
Genotype: Wild Type
Organ: nan
Hardware: BRIC-PDFU (Petri Dish Fixation Unit)

================================================================================
OSD-38
Samples: 36
Age: nan
Cultivar: nan
Genotype: Wild Type
Organ: Seedlings
Hardware: BRIC-PDFU

================================================================================
OSD-427
Samples: 48
Age: nan
Cultivar: nan
Genotype: nan
Organ: nan
Hardware: Vegetable Production System (Veggie)

================================================================================
OSD-437
Samples: 19
Age: 4 {day} | 6 {day}
Cultivar: nan
Genotype: Col-0
Organ: shoot
Hardware: European Modular Cultivation System (EMCS) | NASA Ames, Experimental Reference Module (ERM2)

================================================================================
OSD-522
Samples: 36
Age: nan
Cultivar: nan
Genotype: nan
Organ: nan
Hardware: nan

================================================================================
OSD-678
Samples: 36
Age: nan
Cultivar: nan
Genotype: nan
Organ: Plant Leaves
Hardware: Petri Dish

In [62]:
candidate_table["has_age_metadata"] = candidate_table["age"].notna()

candidate_table["has_cultivar_metadata"] = candidate_table["cultivar"].notna()

candidate_table["has_organ_metadata"] = candidate_table["organ"].notna()

candidate_table["has_light_metadata"] = (
    candidate_table["light_intensity"].notna() |
    candidate_table["light_cycle"].notna() |
    candidate_table["light_source"].notna()
)

In [63]:
candidate_table[
    [
        "id.accession",
        "n_samples_inventory",
        "has_age_metadata",
        "has_cultivar_metadata",
        "has_organ_metadata",
        "has_light_metadata"
    ]
]

,id.accession,n_samples_inventory,has_age_metadata,has_cultivar_metadata,has_organ_metadata,has_light_metadata
0,OSD-120,90,False,False,True,True
8,OSD-193,32,False,False,True,True
12,OSD-217,24,False,False,False,True
13,OSD-218,32,True,True,True,True
14,OSD-219,32,True,True,False,False
16,OSD-223,40,False,False,False,True
18,OSD-281,32,True,False,True,True
22,OSD-314,17,False,False,False,False
24,OSD-321,44,False,False,False,True
27,OSD-37,56,False,False,False,True
28,OSD-38,36,False,False,True,True
32,OSD-427,48,False,False,False,True
36,OSD-437,19,True,False,True,True
51,OSD-522,36,False,False,False,True
58,OSD-678,36,False,False,True,True